app:

  # use the Dockerfile next to this file
  build: .

  volumes:
    - .:/var/www/programming_test

  # sources environment variable configuration for our app
  env_file: .env

  # rely on the RAILS_ENV value of the host machine
  environment:
    RAILS_ENV: $RAILS_ENV

  # makes the app container aware of the DB container
  links:
    - db
    - redis

  # expose the port we configured Unicorn to bind to
  ports:
    - "3000:3000"
db:
  env_file: .env
  image: library/mysql:5.6.22

redis:
  image: redis